using System.Text;
using System.Windows.Controls;
using System.Windows.Input;
using Cairn.Assets;
using Cairn.Ui.Diagnostics;
using Cairn.Ui.Documents;
using Cairn.Ui.Services;
using Cairn.Vpp.Editing;
using Cairn.Vpp.Model;
using Cairn.Vpp.Ui.Documents;
using Cairn.Vpp.Ui.Library;
using Cairn.Vpp.Writing;
using Cairn.Workspace;

namespace Cairn.Vpp.Ui.Diagnostics;

/// <summary>
/// The Packfiles browser (left pane) and the Recent list's packfile entries (<c>Cairn.exe --selftest</c>). Game folders
/// are generated in a temporary folder with tiny packfiles; the user's game data is never touched.
/// </summary>
public static class VppLibrarySelfTests
{
    /// <summary>The shell's settings key of the start page's left tab (MainWindow.StartLeftTabKey).</summary>
    private const string StartTabKey = "shell.leftTab.start";

    private static string NewFolder()
    {
        string folder = Path.Combine(Path.GetTempPath(), "cairn-vpp-library-" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(folder);
        return folder;
    }

    /// <summary>Writes a small valid packfile at <paramref name="path"/> holding <paramref name="entries"/> (or one text file).</summary>
    private static string Packfile(string path, params (string Name, byte[] Bytes)[] entries)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        if (entries.Length == 0) entries = [("readme.txt", Encoding.ASCII.GetBytes("generated by a Cairn self-test\r\n"))];
        var package = VppEdit.AddSources(VppPackage.Empty, [.. entries.Select(e => (e.Name, (VppSource)new MemorySource(e.Bytes)))], VppClashPolicy.KeepBoth).Package;
        VppSaver.Save(package, path, null, CancellationToken.None, VppSaveOptions.Default);
        return path;
    }

    /// <summary>A generated game folder: root, user_maps\multi, two mods (one with a nested folder), an empty mod, and a search folder.</summary>
    private static (string Game, string Search) GameFolder(string folder)
    {
        string game = Path.Combine(folder, "game"), search = Path.Combine(folder, "my packs");
        Packfile(Path.Combine(game, "zeta.vpp"));
        Packfile(Path.Combine(game, "Alpha.vpp"));
        Packfile(Path.Combine(game, "user_maps", "multi", "dm-test.vpp"));
        Packfile(Path.Combine(game, "mods", "ModX", "modx_tables.vpp"));
        Packfile(Path.Combine(game, "mods", "ModX", "deeper", "not_listed.vpp")); // only a mod folder's top level counts
        Packfile(Path.Combine(game, "mods", "Beta", "beta.vpp"));
        Directory.CreateDirectory(Path.Combine(game, "mods", "NoPackfiles"));
        File.WriteAllText(Path.Combine(game, "mods", "NoPackfiles", "readme.txt"), "nothing here");
        File.WriteAllText(Path.Combine(game, "mods", "ModX", "notes.vppx"), "not a packfile");
        Packfile(Path.Combine(search, "custom.vpp"));
        return (game, search);
    }

    private static TabControl? LeftTabs(SelfTestContext ctx) => ctx.MainWindow.FindName("LeftTabs") as TabControl;

    private static IReadOnlyList<string> TabIds(SelfTestContext ctx) => LeftTabs(ctx)?.Items.OfType<TabItem>().Select(t => t.Tag as string ?? "").ToList() ?? [];

    private static string? SelectedTab(SelfTestContext ctx) => (LeftTabs(ctx)?.SelectedItem as TabItem)?.Tag as string;

    [SelfTest("vpp.library-scan")]
    public static async Task LibraryScan(SelfTestContext ctx)
    {
        string folder = NewFolder();
        try
        {
            var (game, search) = GameFolder(folder);
            // the second search folder repeats user_maps\multi: its packfile is listed once, in the first group that has it
            var resolver = new AssetResolver(new AssetResolverOptions { GameDirectory = game, SearchFolders = [search, Path.Combine(game, "user_maps", "multi")] });
            var entries = VppLibraryPanel.Scan(resolver);
            string Describe(VppLibraryEntry e) => $"{e.Group.Label}:{e.Name}";
            ctx.Log("  listed: " + string.Join(", ", entries.Select(Describe)));
            ctx.Check(entries.Select(Describe).SequenceEqual(["Red Faction:Alpha.vpp", "Red Faction:zeta.vpp", @"user_maps\multi:dm-test.vpp",
                @"mods\Beta:beta.vpp", @"mods\ModX:modx_tables.vpp", "my packs:custom.vpp"]),
                "root, user_maps\\multi, each mod folder's top level and the search folder are listed, grouped in that order and by name within a group");
            ctx.Check(entries.Select(e => e.Path).Distinct(StringComparer.OrdinalIgnoreCase).Count() == entries.Count, "a folder listed twice does not list its packfiles twice");
            ctx.Check(entries.All(e => e.Size > 0 && Path.IsPathFullyQualified(e.Path) && e.SizeText.Length > 0), "every row has a full path and a size");
            ctx.Check(entries.First(e => e.Name == "custom.vpp").Group.Folder == search, "a search folder's heading is its name; the group keeps the full path (tooltip)");
            ctx.Check(VppLibraryPanel.Scan(new AssetResolver(new AssetResolverOptions())).Count == 0, "no game folder and no search folders: nothing listed");

            // the panel over the same folders: filter by name or by folder heading
            var panel = new VppLibraryPanel(ctx.Shell, () => resolver);
            await panel.ReloadAsync();
            ctx.Check(panel.Entries.Count == 6 && panel.Shown.Count == 6, $"the panel lists all six ({panel.Entries.Count})");
            ctx.Check(panel.StatusText == "6 packfiles in 5 folders", $"footer counts packfiles and folders ({panel.StatusText})");
            panel.Filter = "TABLES";
            ctx.Check(panel.Shown.Select(e => e.Name).SequenceEqual(["modx_tables.vpp"]), "the filter matches names, ignoring case");
            ctx.Check(panel.StatusText == "1 of 6 packfiles", $"footer shows the filtered count ({panel.StatusText})");
            panel.Filter = "user_maps";
            ctx.Check(panel.Shown.Select(e => e.Name).SequenceEqual(["dm-test.vpp"]), "the filter matches the folder heading");
            panel.Filter = "mods\\";
            ctx.Check(panel.Shown.Count == 2, "a folder prefix shows that folder's packfiles");
            panel.Filter = "no such packfile";
            ctx.Check(panel.Shown.Count == 0 && panel.StatusText == "0 of 6 packfiles", "a filter matching nothing shows none");
            panel.Filter = "";
            ctx.Check(panel.Shown.Count == 6, "clearing the filter shows every packfile again");

            // Refresh lists a packfile added since
            Packfile(Path.Combine(game, "user_maps", "multi", "dm-new.vpp"));
            await panel.ReloadAsync();
            ctx.Check(panel.Entries.Any(e => e.Name == "dm-new.vpp"), "Refresh lists a packfile added since the last listing");

            // opening a row opens the packfile in a tab; opening it again brings that tab forward
            var alpha = panel.Entries.First(e => e.Name == "Alpha.vpp");
            int before = ctx.Shell.Documents.Count;
            ctx.Check(panel.Open(alpha) && ctx.Shell.ActiveDocument is VppDocument { FilePath: { } p } && string.Equals(p, alpha.Path, StringComparison.OrdinalIgnoreCase),
                "Open opens the packfile in a packfile tab");
            var opened = ctx.Shell.ActiveDocument;
            ctx.Check(panel.Open(alpha) && ReferenceEquals(ctx.Shell.ActiveDocument, opened) && ctx.Shell.Documents.Count == before + 1, "opening it again activates the same tab");
            if (opened is not null) ctx.Shell.Close(opened);
        }
        finally
        {
            Work.VppWorkFolder.TryDeleteFolder(folder);
        }
    }

    [SelfTest("vpp.library-collapse")]
    public static async Task LibraryCollapse(SelfTestContext ctx)
    {
        string folder = NewFolder();
        System.Windows.Window? host = null;
        try
        {
            var (game, search) = GameFolder(folder);
            var resolver = new AssetResolver(new AssetResolverOptions { GameDirectory = game, SearchFolders = [search] });
            var panel = new VppLibraryPanel(ctx.Shell, () => resolver);
            await panel.ReloadAsync();
            VppLibraryGroupNode Node(string label) => panel.Groups.First(g => g.Label == label);
            ctx.Check(panel.Groups.Count == 5 && panel.Groups.All(g => g.IsExpanded), $"every folder heading starts expanded ({panel.Groups.Count})");

            // shown off screen (never activated) so the tree's items exist
            host = new System.Windows.Window
            {
                Content = panel, Width = 320, Height = 600, Left = -20000, Top = -20000, ShowActivated = false, ShowInTaskbar = false,
                WindowStyle = System.Windows.WindowStyle.None, Title = "Packfiles self-test",
            };
            host.Show();
            await ctx.SettleAsync();
            TreeViewItem? Item(VppLibraryGroupNode node) { panel.Tree.UpdateLayout(); return panel.Tree.ItemContainerGenerator.ContainerFromItem(node) as TreeViewItem; }
            var rf = Node("Red Faction");
            var item = Item(rf);
            var arrow = item?.Template?.FindName("Expander", item) as System.Windows.Controls.Primitives.ToggleButton;
            ctx.Check(arrow is not null && ReferenceEquals(arrow.Style, System.Windows.Application.Current.TryFindResource("TreeExpanderToggle")) && arrow.IsChecked == true,
                "a heading has the Animations library's expand arrow (TreeExpanderToggle), shown open");

            // the arrow collapses and expands (as a click does, through its automation pattern)
            if (arrow is not null)
            {
                var toggle = (System.Windows.Automation.Provider.IToggleProvider)new System.Windows.Automation.Peers.ToggleButtonAutomationPeer(arrow);
                toggle.Toggle();
                ctx.Check(!rf.IsExpanded && item!.IsExpanded == false && panel.IsCollapsed(rf.Folder), "the arrow collapses the heading (and the panel remembers it)");
                toggle.Toggle();
                ctx.Check(rf.IsExpanded && !panel.IsCollapsed(rf.Folder), "... and expands it again");
            }

            // Left and Right on a selected heading, as in the library's tree
            if (item is not null && System.Windows.PresentationSource.FromVisual(item) is { } source)
            {
                void Press(Key key) => item.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice, source, 0, key) { RoutedEvent = Keyboard.KeyDownEvent });
                item.IsSelected = true;
                item.Focus(); // the tree acts on the focused item (logical focus: the test window is never activated)
                Press(Key.Left);
                ctx.Check(!rf.IsExpanded, "Left collapses the selected heading");
                Press(Key.Right);
                ctx.Check(rf.IsExpanded, "Right expands it");
            }
            else ctx.Check(false, "the heading's tree item exists");

            // remembered across a refresh
            Node(@"mods\ModX").IsExpanded = false;
            await panel.ReloadAsync();
            ctx.Check(!Node(@"mods\ModX").IsExpanded && panel.Groups.Count(g => g.IsExpanded) == 4, "a collapsed heading stays collapsed after Refresh; the others stay expanded");

            // filtering shows matching headings expanded, without forgetting the choice
            panel.Filter = "modx";
            ctx.Check(panel.Groups.Count == 1 && Node(@"mods\ModX").IsExpanded, "while filtering, the matching heading shows expanded");
            ctx.Check(Item(Node(@"mods\ModX"))?.IsExpanded == true, "... in the tree too");
            Node(@"mods\ModX").IsExpanded = false; // toggled while filtering: not remembered
            panel.Filter = "";
            ctx.Check(!Node(@"mods\ModX").IsExpanded && panel.Groups.Count == 5, "clearing the filter restores the collapsed heading");
            ctx.Check(Item(Node(@"mods\ModX"))?.IsExpanded == false, "... in the tree too");
            Node(@"mods\ModX").IsExpanded = true;
            panel.Filter = "x";
            panel.Filter = "";
            ctx.Check(Node(@"mods\ModX").IsExpanded && !panel.IsCollapsed(Node(@"mods\ModX").Folder), "expanding it again is remembered as well");

            // the diagnostic option's route: collapse by heading
            panel.Collapse(["Red Faction", "my packs"]);
            ctx.Check(!Node("Red Faction").IsExpanded && !Node("my packs").IsExpanded && Node(@"user_maps\multi").IsExpanded, "headings collapse by label");
        }
        finally
        {
            host?.Close();
            Work.VppWorkFolder.TryDeleteFolder(folder);
        }
    }

    [SelfTest("vpp.library-tabs")]
    public static async Task LibraryTabs(SelfTestContext ctx)
    {
        var module = ctx.Shell.Modules.OfType<VppModule>().First();
        if (LeftTabs(ctx) is null) { ctx.Skip("the main window has no left pane"); return; }
        if (ctx.Shell.Documents.Any(d => d.IsDirty)) { ctx.Skip("a document with unsaved changes is open"); return; }
        string folder = NewFolder();
        var settings = ctx.Shell.Settings;
        string vppKey = "shell.leftTab.vpp";
        string? savedStart = settings.Get<string>(StartTabKey), savedVpp = settings.Get<string>(vppKey);
        try
        {
            settings.Set<string>(StartTabKey, null); // a fresh settings state
            settings.Set<string>(vppKey, null);
            foreach (var d in ctx.Shell.Documents.ToList()) ctx.Shell.Close(d);
            // the start page is reached on activation: open and close a packfile so the shell re-fills the panes
            string path = Packfile(Path.Combine(folder, "tabs.vpp"));
            ctx.Check(ctx.Shell.OpenFile(path) && ctx.Shell.ActiveDocument is VppDocument, "a packfile opens");
            var doc = ctx.Shell.ActiveDocument!;
            await ScreenshotContext.YieldAsync();
            ctx.Check(TabIds(ctx).SequenceEqual(["vpp.types", VppModule.LibraryPanelId]), $"beside a packfile: File types, then Packfiles ({string.Join(", ", TabIds(ctx))})");
            ctx.Check(SelectedTab(ctx) == "vpp.types", $"File types is the packfile's default tab ({SelectedTab(ctx)})");
            ctx.Shell.Close(doc);
            await ScreenshotContext.YieldAsync();
            ctx.Check(ctx.Shell.ActiveDocument is null && TabIds(ctx).FirstOrDefault() == VppModule.LibraryPanelId, $"the start page's first left tab is Packfiles ({string.Join(", ", TabIds(ctx))})");
            ctx.Check(SelectedTab(ctx) == VppModule.LibraryPanelId, $"... and it is selected in a fresh settings state ({SelectedTab(ctx)})");
            ctx.Check(LeftTabs(ctx)?.SelectedContent is VppLibraryPanel panel && ReferenceEquals(panel, module.Library), "the tab shows the module's one Packfiles panel");

            // another module's document: no Packfiles tab
            if (module.CairnOpens("x.tbl"))
            {
                string table = Path.Combine(folder, "plain.tbl");
                File.WriteAllText(table, "#General\r\n$Name: \"cairn test\"\r\n#End\r\n", Encoding.ASCII);
                ctx.Check(ctx.Shell.OpenFile(table) && ctx.Shell.ActiveDocument is { } t && !(t is VppDocument), "a table opens");
                var tableDoc = ctx.Shell.ActiveDocument;
                await ScreenshotContext.YieldAsync();
                ctx.Check(!TabIds(ctx).Contains(VppModule.LibraryPanelId), $"a table's left pane has no Packfiles tab ({string.Join(", ", TabIds(ctx))})");
                if (tableDoc is not null) ctx.Shell.Close(tableDoc);
            }
            else ctx.Log("  (table module not loaded: the other-document check is skipped)");

            // the start page remembers its own tab: choose another one, visit a packfile (File types), come back
            var tabs = LeftTabs(ctx)!;
            if (tabs.Items.OfType<TabItem>().FirstOrDefault(t => (t.Tag as string) != VppModule.LibraryPanelId) is { } other)
            {
                tabs.SelectedItem = other; // as a click does
                ctx.Check(settings.Get<string>(StartTabKey) == (string)other.Tag, $"choosing a start-page tab is remembered under {StartTabKey}");
                ctx.Shell.OpenFile(path);
                var again = ctx.Shell.ActiveDocument;
                await ScreenshotContext.YieldAsync();
                ctx.Check(SelectedTab(ctx) == "vpp.types", "a packfile still opens on File types");
                if (again is not null) ctx.Shell.Close(again);
                await ScreenshotContext.YieldAsync();
                ctx.Check(SelectedTab(ctx) == (string)other.Tag, $"closing the last document returns to the remembered start tab ({SelectedTab(ctx)})");
            }
            else ctx.Log("  (only one start-page tab in this build: the start-tab memory check is skipped)");
        }
        finally
        {
            settings.Set(StartTabKey, savedStart);
            settings.Set(vppKey, savedVpp);
            Work.VppWorkFolder.TryDeleteFolder(folder);
        }
    }

    /// <summary>
    /// Screenshot options: <c>--vpp-open-in-cairn name</c> opens that entry of the active packfile in a Cairn tab (as the
    /// list's "Open in Cairn" does); <c>--close-documents</c> then closes every tab, e.g. to capture the start page's
    /// Recent list afterwards.
    /// </summary>
    [ScreenshotStep(900)]
    public static async Task OpenInCairnThenClose(ScreenshotContext ctx)
    {
        if (ctx.Options.TryGetValue("vpp-open-in-cairn", out var name) && ctx.Shell.ActiveDocument is VppDocument doc && doc.Current.Find(name) is { } item)
        {
            await doc.Commands.OpenInCairnAsync(item);
            await ctx.SettleAsync();
        }
        if (ctx.Options.ContainsKey("close-documents"))
            foreach (var d in ctx.Shell.Documents.Where(d => !d.IsDirty).ToList()) ctx.Shell.Close(d);
    }

    [SelfTest("vpp.recent-entry")]
    public static async Task RecentEntry(SelfTestContext ctx)
    {
        var module = ctx.Shell.Modules.OfType<VppModule>().First();
        if (!module.CairnOpens("x.tbl")) { ctx.Skip("needs the table module in the build"); return; }
        string folder = NewFolder();
        var opened = new List<IDocument>();
        try
        {
            string path = Packfile(Path.Combine(folder, "recent.vpp"), ("recent_info.tbl", Encoding.ASCII.GetBytes("#General\r\n$Name: \"recent\"\r\n#End\r\n")));
            if (!ctx.Check(ctx.Shell.OpenFile(path) && ctx.Shell.ActiveDocument is VppDocument, "the packfile opens")) return;
            var doc = (VppDocument)ctx.Shell.ActiveDocument!;
            opened.Add(doc);
            var known = ctx.Shell.Documents.ToHashSet();
            await doc.Commands.OpenInCairnAsync(doc.Current.Find("recent_info.tbl")!);
            var table = ctx.Shell.Documents.FirstOrDefault(d => !known.Contains(d));
            if (!ctx.Check(table?.FilePath is not null, "Open in Cairn opens the entry's work copy in a tab")) return;
            opened.Add(table!);
            string copy = table!.FilePath!;
            ctx.Check(module.IsWorkCopy(copy) && !module.IsWorkCopy(path), "the work copy is in the work area; the packfile is not");
            ctx.Check(module.ArchiveEntryOf(copy) is { } e && string.Equals(e.ArchivePath, Path.GetFullPath(path), StringComparison.OrdinalIgnoreCase) && e.EntryName == "recent_info.tbl",
                "the work copy maps back to its packfile and entry");
            var recent = ctx.Shell.Settings.RecentFiles;
            string expected = RecentFilesList.EntryReference(path, "recent_info.tbl");
            ctx.Check(recent.FirstOrDefault() == expected, $"the Recent list records the entry, not the work copy ({recent.FirstOrDefault()})");
            ctx.Check(!recent.Any(module.IsWorkCopy), "no Recent item is a work-area path");
            ctx.Check(RecentFilesList.TryParseEntry(expected, out var a, out var n) && string.Equals(a, Path.GetFullPath(path), StringComparison.OrdinalIgnoreCase) && n == "recent_info.tbl",
                "the entry reference reads back as packfile + entry");

            // reopening: through the module, as the shell's Recent list does
            ctx.Shell.Close(table);
            known = ctx.Shell.Documents.ToHashSet();
            ctx.Check(module.OpenArchiveEntry(path, "recent_info.tbl"), "reopening the entry is accepted");
            IDocument? reopened = null;
            for (int i = 0; i < 100 && reopened is null; i++)
            {
                await Task.Delay(100);
                reopened = ctx.Shell.Documents.FirstOrDefault(d => !known.Contains(d));
            }
            if (reopened is not null) opened.Add(reopened);
            ctx.Check(reopened?.FilePath is { } again && module.ArchiveEntryOf(again)?.EntryName == "recent_info.tbl", "it opens the entry again from a fresh work copy");
            ctx.Check(ctx.Shell.Settings.RecentFiles.FirstOrDefault() == expected, "the entry stays at the top of the Recent list");

            int errors = (ctx.Shell.Dialogs as DialogService)?.CollectErrors?.Count ?? 0;
            ctx.Check(!module.OpenArchiveEntry(path, "gone.tbl"), "an entry no longer in the packfile is refused");
            ctx.Check(((ctx.Shell.Dialogs as DialogService)?.CollectErrors?.Count ?? errors + 1) > errors, "... with an error message");
        }
        finally
        {
            foreach (var d in Enumerable.Reverse(opened)) if (ctx.Shell.Documents.Contains(d)) ctx.Shell.Close(d);
            Work.VppWorkFolder.TryDeleteFolder(folder);
        }
    }
}
