using Cairn.Formats.Imaging;
using Cairn.Vfx.Editing;
using Cairn.Vfx.Formats;
using Cairn.Vfx.Ui.Dialogs;

namespace Cairn.Vfx.SampleGen;

/// <summary>
/// The VFX sample set: every "New from template" effect, one effect per primitive shape, and the procedural
/// placeholder texture they all use. Nothing here comes from the game.
/// </summary>
public static class VfxSampleSet
{
    public const string TextureName = "cairn_placeholder.tga";

    /// <summary>File name -> effect, in a stable order.</summary>
    public static IReadOnlyList<(string Name, VfxFile File)> Effects()
    {
        var list = VfxCreation.TemplateNames.Select(n => (n.Replace(" ", "_") + ".vfx", VfxCreation.Template(n, TextureName))).ToList();
        foreach (var kind in Enum.GetValues<VfxPrimitiveKind>())
        {
            var request = new VfxPrimitiveRequest(kind, kind.ToString(), Texture: TextureName, Frames: 15,
                SizeB: kind is VfxPrimitiveKind.Disc ? 0.5f : kind is VfxPrimitiveKind.FacingRod ? 3 : 1);
            list.Add(($"Primitive_{kind}.vfx", VfxCreation.AddPrimitive(VfxBuilder.NewFile(), request).File));
        }
        return list;
    }

    /// <summary>A 64x64 soft white glow with a faint ring, alpha matching brightness (works additive or alpha-blended).</summary>
    public static byte[] PlaceholderTexture()
    {
        const int size = 64;
        var image = new BgraImage(size, size);
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                float dx = (x + 0.5f) / size * 2 - 1, dy = (y + 0.5f) / size * 2 - 1, r = MathF.Sqrt(dx * dx + dy * dy);
                float glow = MathF.Max(0, 1 - r); glow *= glow;
                float ring = MathF.Max(0, 1 - MathF.Abs(r - 0.7f) * 12) * 0.5f;
                float v = Math.Clamp(glow + ring, 0, 1);
                int i = (y * size + x) * 4;
                image.Pixels[i] = (byte)(255 * v);                         // B
                image.Pixels[i + 1] = (byte)(255 * MathF.Min(1, v * 1.1f)); // G (slightly warm)
                image.Pixels[i + 2] = (byte)(255 * MathF.Min(1, v * 1.2f)); // R
                image.Pixels[i + 3] = (byte)(255 * v);                     // A
            }
        return TgaWriter.Write(image, includeAlpha: true);
    }

    public const string Readme = """
        # VFX samples

        Generated by `tools/Cairn.Vfx.SampleGen` (`dotnet run --project tools/Cairn.Vfx.SampleGen`); do not edit by hand.
        Nothing here comes from the game.

        - `Additive_flash.vfx`, `Scrolling_beam.vfx`, `Ring_shockwave.vfx`, `Particle_fountain.vfx`: the effects
          offered by Effect > New from template.
        - `Primitive_*.vfx`: one effect per shape offered by Effect > Add > Primitive (15 frames, one image material).
        - `cairn_placeholder.tga`: a procedural 64x64 glow that every sample uses as its texture. To see the
          samples in the game, copy this texture next to them (or replace it with your own under the same name).
        """;

    /// <summary>Writes every sample into <paramref name="folder"/> and returns the paths written.</summary>
    public static IReadOnlyList<string> WriteAll(string folder)
    {
        Directory.CreateDirectory(folder);
        var written = new List<string>();
        void Write(string name, byte[] bytes) { var p = Path.Combine(folder, name); File.WriteAllBytes(p, bytes); written.Add(p); }
        foreach (var (name, file) in Effects()) Write(name, VfxWriter.Write(file));
        Write(TextureName, PlaceholderTexture());
        Write("README.md", System.Text.Encoding.UTF8.GetBytes(Readme.Replace("\r\n", "\n") + "\n"));
        return written;
    }
}
